HRManagement/Controllers/DepartmentController.cs
using HRManagement.Models;
using HRManagement.Services;
using Microsoft.AspNetCore.Mvc;

namespace HRManagement.Controllers
{
	public class DepartmentController : Controller
	{
		private readonly IDepartmentService _departmentService;
		public DepartmentController(IDepartmentService departmentService)
		{
			_departmentService = departmentService;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Delete(int id)
		{
			bool deleted = _departmentService.DeleteDepartment(id);

			if (deleted)
				return Json("success");
			else
				return BadRequest("Invalid ID");
		}

		[HttpPost]
		public IActionResult Edit(int id, string code, string name)
		{
			Department des = new() { Id = id, Code = code, Name = name };

			if (_departmentService.UpdateDepartment(des))
				return Json("success");
			else
				return BadRequest("Department code already exists.");
		}

		public IActionResult Add()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Add(string code, string name)
		{
			Department dep = new() { Code = code, Name = name };

			if (_departmentService.AddDepartment(dep))
				return Json("success");
			else
				return BadRequest("Department code already exists.");
		}

		[HttpGet]
		public IActionResult GetDepsPartial()
		{
			List<Department> departments = _departmentService.GetDepartments();
			return PartialView("_Departments", departments);
		}
	}
}

HRManagement/Controllers/EmployeeController.cs
using ExcelDataReader;
using HRManagement.Models;
using HRManagement.Services;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Data;

namespace HRManagement.Controllers
{
	public class EmployeeController : Controller
	{
		private readonly IEmployeesService _employeeService;
		public EmployeeController(IEmployeesService employeeService)
		{
			_employeeService = employeeService;
		}

		public IActionResult Index(int rowlength, string page = "first")
		{
			int employeeCount = _employeeService.GetEmployeesCount();
			if (employeeCount == 0)
				return View(new EmployeeViewModel());

			if (rowlength == 0)
				rowlength = 10;

			int pageCount = (int)Math.Ceiling((employeeCount / Convert.ToDecimal(rowlength)));

			int parsedPage;
			if (page == null || page == "" || page == "first")
				parsedPage = 1;
			else if (page == "last")
				parsedPage = pageCount;
			else
			{
				bool canParse = int.TryParse(page, out parsedPage);
				if (!canParse) parsedPage = 1;
			}

			if (parsedPage == 0)
				parsedPage = 1;

			List<Employee> employees;

			employees = _employeeService.GetEmployees(parsedPage, rowlength);


			EmployeeViewModel model = new()
			{
				Employees = employees,
				TotalPages = pageCount,
				CurrentPage = parsedPage,
				RowLength = rowlength
			};

			return View(model);
		}

		[HttpPost]
		public IActionResult Delete(int id)
		{
			bool deleted = _employeeService.DeleteEmployee(id);

			if (deleted)
				return Json("success");
			else
				return BadRequest("Invalid ID");
		}

		public IActionResult View(int id)
		{
			Employee? employee = _employeeService.GetEmployee(id);
			if (employee == null)
				return NotFound("Invalid ID");
			return View(employee);
		}

		public IActionResult Edit(int id)
		{
			Employee? employee = _employeeService.GetEmployee(id);
			if (employee == null)
				return NotFound("Invalid ID");
			return View(employee);
		}

		[HttpPost]
		public IActionResult Edit(Employee emp, IFormFile? EmployeeImage)
		{
			if (!ModelState.IsValid)
				return View("Edit", emp);

			if (EmployeeImage != null)
			{
				if (EmployeeImage.Length > 0 && EmployeeImage.Length < 2097152 && EmployeeImage.ContentType.Contains("image"))
					//Convert EmployeeImage to byte and save to database
					using (MemoryStream ms = new MemoryStream())
					{
						EmployeeImage.CopyTo(ms);
						emp.Image = ms.ToArray();
					}
				else
					ModelState.AddModelError("CustomError", "File must be a valid image and less than 2MB.");
			}
			else
			{
				Employee? _employee = _employeeService.GetEmployee(emp.Id);
				if (_employee != null)
					emp.Image = _employee.Image;
			}
			if (_employeeService.UpdateEmployee(emp))
			{
				return RedirectToAction("Index");
			}
			else
			{
				ModelState.AddModelError("CustomError", "Failed to edit employee.");
				return View("Edit", emp);
			}
		}

		public IActionResult Add()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Add(Employee emp, IFormFile EmployeeImage)
		{
			if (!ModelState.IsValid)
				return View("Add", emp);

			if (EmployeeImage != null)
			{
				if (EmployeeImage.Length > 0 && EmployeeImage.Length < 2097152 && EmployeeImage.ContentType.Contains("image"))
					//Convert EmployeeImage to byte array
					using (MemoryStream ms = new())
					{
						EmployeeImage.CopyTo(ms);
						emp.Image = ms.ToArray();
					}
				else
					ModelState.AddModelError("CustomError", "File must be a valid image and less than 2MB.");

			}
			if (_employeeService.AddEmployee(emp))
			{
				return RedirectToAction("Index");
			}
			else
			{
				ModelState.AddModelError("CustomError", "Employee code already registered.");
				return View("Add", emp);
			}
		}

		public IActionResult Import()
		{
			try
			{
				var excFile = Request.Form.Files[0];

				using var reader = ExcelReaderFactory.CreateReader(excFile.OpenReadStream());

				var result = reader.AsDataSet(new ExcelDataSetConfiguration()
				{
					ConfigureDataTable = (_) => new ExcelDataTableConfiguration()
					{
						UseHeaderRow = true
					}
				});

				DataTableCollection tables = result.Tables;

				JObject ImportResults = new();

				foreach (DataTable dt in tables)
				{
					int success = 0, failed = 0;

					foreach (DataRow dr in dt.Rows)
					{
						Employee emp = new()
						{
							EmployeeCode = dr["EmployeeCode"].ToString(),
							EmployeeName = dr["EmployeeName"].ToString(),
							AppointedBy = dr["AppointedBy"].ToString(),
							JoinDate = DateTime.Parse(dr["JoinDate"].ToString()),
							Qualification = dr["Qualification"].ToString(),
							Gender = dr["Gender"].ToString(),
							DateOfBirth = DateTime.Parse(dr["DateOfBirth"].ToString()),
							Religion = dr["Religion"].ToString(),
							MaritalStatus = dr["MaritalStatus"].ToString(),
							Dependants = Convert.ToInt32(dr["Dependants"]),
							Email = dr["Email"].ToString(),
							PostBox = dr["PostBox"].ToString(),
							Country = dr["Country"].ToString(),
							City = dr["City"].ToString(),
							Landline = Convert.ToInt32(dr["Landline"]),
							Mobile = Convert.ToInt32(dr["Mobile"]),
							Address = dr["Address"].ToString()
						};

						if (_employeeService.AddEmployee(emp))
							success++;
						else
							failed++;
					}

					//create JSON object in format: TableName : {success, failed}
					ImportResults.Add(dt.TableName, new JObject
					{
						{ "success", success },
						{ "failed", failed }
					});

				}

				return Content(ImportResults.ToString(), "application/json");

			}
			catch (Exception ex)
			{
				return BadRequest(ex.Message);
			}
		}
	}
}

HRManagement/Controllers/LoginController.cs
using HRManagement.Models;
using HRManagement.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace HRManagement.Controllers
{
	public class LoginController : Controller
	{
		private readonly IAccountsService _accountsService;
		private readonly IConfiguration _configuration;

		public LoginController(IAccountsService accountsService, IConfiguration configuration)
		{
			_accountsService = accountsService;
			_configuration = configuration;
		}

		[HttpGet]
		public IActionResult Index()
		{
			if (TempData.ContainsKey("Message"))
			{
				ViewBag.Message = TempData["Message"];
			}
			return View();
		}

		[HttpPost]
		public IActionResult Index(string userEmail, string userPassword, string userRemember)
		{
			User? employee = _accountsService.GetEmployee(userEmail, userPassword);
			if (employee == null)
			{
				ModelState.AddModelError("CustomError", "Invalid email or password.");
				return View("Index");
			}
			else
			{
				DateTime expiry = DateTime.Now.AddHours(4);
				if (!string.IsNullOrEmpty(userRemember) && userRemember.Equals("on"))
					expiry = DateTime.Now.AddDays(7);
				
				List<Claim> authClaims = new()
				{
					new Claim(ClaimTypes.Name, userEmail),
					new Claim(ClaimTypes.Role, "Admin"),
					new Claim(ClaimTypes.Email, userEmail),
					new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
					new Claim(JwtRegisteredClaimNames.Iat, DateTime.UtcNow.ToString())
				};
				
				SymmetricSecurityKey authSigninKey = new(Encoding.UTF8.GetBytes(_configuration["JWT:Secret"]));

				JwtSecurityToken token = new(
					issuer: _configuration["JWT:Issuer"],
					audience: _configuration["JWT:Audience"],
					claims: authClaims,
					expires: expiry,
					signingCredentials: new SigningCredentials(authSigninKey, SecurityAlgorithms.HmacSha256Signature)
				);

				JwtSecurityTokenHandler jwtSecurityTokenHandler = new();
				string savedToken = jwtSecurityTokenHandler.WriteToken(token);
				
				HttpContext.Session.SetString("Token", savedToken);

				return RedirectToAction("Index", "Home");
			}
		}

		public IActionResult Logout()
		{
			HttpContext.Session.Clear();
			return RedirectToAction("Index", "Home");
		}
	}
}

HRManagement/Controllers/SignupController.cs
using HRManagement.Models;
using HRManagement.Services;
using Microsoft.AspNetCore.Mvc;

namespace HRManagement.Controllers
{
	public class SignupController : Controller
	{
		private readonly IAccountsService _accountsService;

		public SignupController(IAccountsService accountsService)
		{
			_accountsService = accountsService;
		}

		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Index(User emp)
		{
			if (!ModelState.IsValid)
			{
				return View("Index", emp);
			}

			if (_accountsService.AddEmployee(emp))
			{
				return RedirectToAction("Index", "Login");
			}
			else
			{
				ModelState.AddModelError("CustomError", "Email already registered.");
				return View("Index", emp);
			}
		}
	}
}

HRManagement/Views/Shared/Unauthorized.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Unauthorized</title>
</head>
<body>
	<p>Not authorized!</p>
</body>
</html>

HRManagement/Views/Shared/_Layout.cshtml
@inject IHttpContextAccessor Accessor

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - HR Management</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link href="~/lib/fontawesome-free/css/all.min.css" rel="stylesheet" />
	<link href="~/lib/sbadmin2/sb-admin-2.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">HR Management</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">

						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Designation" asp-action="Index">Designations</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
						</li>
						@if (Accessor?.HttpContext?.User?.Identity?.IsAuthenticated ?? false)
						{
							<li class="nav-item ms-auto">
								<a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
							</li>
						}
						else
						{
							<li class="nav-item ms-auto">
								<a class="nav-link text-light" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
							</li>
						}
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Signup" asp-action="Index">Signup</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>

	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted bg-dark">
		<div class="container">
			&copy; 2022 - HR Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/sbadmin2/sb-admin-2.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>